name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x
      - name: Create PostgreSQL service container  
        uses: docker/whalesay/whalesay@v1  
        with:    
          image: postgres:14
      - name: Connect to PostgreSQL  
        run: |   
          gitPGPASSWORD=admin psql -h localhost -p 5432 -U postgres
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle
          gem install --no-document rspec -v '>=3.0, < 4.0'
      - name: RSpec Report
        run: rspec --force-color --format documentation
